influx:
  url: http://localhost:8086/ # URL to connect to InfluxDB.
  token: my-token # Token to use for the authorization.
  org: my-org # Default destination organization for writes and queries.
  bucket: my-bucket # Default destination bucket for writes.
  logLevel: BODY # The log level for logging the HTTP request and HTTP response. (Default: NONE)
  readTimeout: 5s # Read timeout for OkHttpClient. (Default: 10s)
  writeTimeout: 5s # Write timeout for OkHttpClient. (Default: 10s)
  connectTimeout: 5s # Connection timeout for OkHttpClient. (Default: 10s)
management:
  metrics:
    export:
      influx:
        bucket: my-bucket
        org: my-org
        token: my-token